"""
Populates the database with the starter dataset.
Run with: python seed.py
Safe to re-run — it truncates existing tables first.

Each look is a dict — scene_label/designer/era_decade/description/colors/materials
are the "always fill in" fields; image_file, brand, and accessories are optional
extras (brand is left blank across this starter set on purpose: most of these
are bespoke film costumes rather than real-world branded garments, and we'd
rather leave it empty than guess).
"""
import db

DATA = [
    # (film_title, year, director, genre, character, [ look dicts ])
    ("Marie Antoinette", 2006, "Sofia Coppola", "period-drama", "Marie Antoinette", [
        dict(scene_label="Cake & champagne scene", designer="Milena Canonero", era_decade="1770s",
             description="A pastel confection of a gown, styled to look almost edible — part of the film's deliberately anachronistic, sugar-pop take on Versailles.",
             colors=["pastel-pink", "mint", "gold"], materials=["silk", "tulle"],
             image_url="https://spxfashion.wordpress.com/wp-content/uploads/2012/10/2006_marie_antoinette_005.jpg"),
    ]),
    ("Pride & Prejudice", 2005, "Joe Wright", "period-drama", "Elizabeth Bennet", [
        dict(scene_label="Muddy-hem morning walk", designer="Jacqueline Durran", era_decade="1790s",
             description="A simple cream empire-waist dress, deliberately less polished than her sisters' — costume as characterization.",
             colors=["ivory", "blue"], materials=["cotton"], image_file="elizabeth-bennet-prideandprejudice-hayfield.jpg",
             accessories="embroidered wool shawl"),
        dict(scene_label="Sick day at Netherfield", designer="Jacqueline Durran", era_decade="1790s",
             description="A plain wool day dress worn while nursing a cold at Netherfield — deliberately unglamorous, in keeping with the film's grounded, lived-in take on Regency dress.",
             colors=["burgundy"], materials=["wool"], image_file="keira-prideandprejudice-brownmonotone.jpg"),
    ]),
    ("Phantom Thread", 2017, "Paul Thomas Anderson", "period-drama", "The Countess", [
        dict(scene_label="Gala entrance", designer="Mark Bridges", era_decade="1950s",
             description="A blush-pink lace gown from the House of Woodcock, tailored with the obsessive precision the film is built around.",
             colors=["pastel-pink", "ivory"], materials=["lace", "satin"],
             image_file="countess-phantomthread-blushgown.webp"),
    ]),
    ("Star Wars: Episode II", 2002, "George Lucas", "sci-fi", "Padmé Amidala", [
        dict(scene_label="Meadow picnic dress", designer="Trisha Biggar", era_decade="n/a",
             description="A flowing, softly draped gown that reads almost medieval — a rare moment of romantic vulnerability in Padmé's wardrobe.",
             colors=["white", "gold"], materials=["silk", "velvet"], image_file="padme-ombredress.jpg"),
        dict(scene_label="Naboo diplomatic gown", designer="Trisha Biggar", era_decade="n/a",
             description="An elaborate gold-and-cream gown with an ornate headpiece, part of Padmé's formal diplomatic wardrobe on Naboo.",
             colors=["gold", "ivory"], materials=["brocade", "silk"], image_file="padme-orange.jpg",
             accessories="ornate gold headpiece"),
    ]),
    ("Mad Max: Fury Road", 2015, "George Miller", "sci-fi", "Furiosa", [
        dict(scene_label="Wasteland warlord look", designer="Jenny Beavan", era_decade="n/a",
             description="Rust-toned utility wear built from scavenged materials — practical, armored, and completely without vanity.",
             colors=["rust", "khaki"], materials=["leather", "denim"],
             image_file="charlizetheron-furyroad-warrigcloseup.png"),
    ]),
    ("The Devil Wears Prada", 2006, "David Frankel", "fashion-world", "Miranda Priestly", [
        dict(scene_label="Office entrance", designer="Patricia Field", era_decade="2000s",
             description="A dark fur-collared coat, an early mock-up of Runway tucked under one arm — Miranda commanding a room before she even speaks.",
             colors=["black"], materials=["fur"], image_file="mirandapriestly-devilwearsprada-officeentrance.png"),
        dict(scene_label="Boardroom pinstripe suit", designer="Patricia Field", era_decade="2000s",
             description="A cropped pinstripe jacket and skirt worn over a stark white blouse — Miranda's daytime uniform of understated, terrifying authority.",
             colors=["black", "grey"], materials=["wool", "cotton"], image_file="miranda-devilwearsprada-blacksuit.jpg",
             accessories="hoop earrings"),
        dict(scene_label="Fox fur exit coat", designer="Patricia Field", era_decade="2000s",
             description="An oversized red fox fur coat, worn leaving the office — equal parts armor and spectacle.",
             colors=["burgundy", "black"], materials=["fur"], image_file="miranda-devilwearsprada-redfur.jpg",
             accessories="leather tote bag"),
    ]),
    ("The Devil Wears Prada", 2006, "David Frankel", "fashion-world", "Andy Sachs", [
        dict(scene_label="Paris finale look", designer="Patricia Field", era_decade="2000s",
             description="A structured black-and-emerald dress worn walking through Paris — marking Andy's full arrival into the fashion world she once mocked.",
             colors=["black", "green"], materials=["silk"], image_file="andysachs-devilwearsprada-parisfinale.webp"),
        dict(scene_label="First day at Runway", designer="Patricia Field", era_decade="2000s",
             description="The cable-knit sweater and plaid skirt Andy wears before her transformation — sensible, collegiate, completely wrong for the building she's walking into.",
             colors=["blue", "grey"], materials=["wool", "cotton"], image_file="andy-devilwearsprada-blyesweater.jpg"),
        dict(scene_label="Times Square trench", designer="Patricia Field", era_decade="2000s",
             description="A cream trench thrown over a plaid skirt, marking the midpoint of Andy's wardrobe evolution.",
             colors=["ivory", "blue"], materials=["cotton", "wool"], image_file="andy-devilwearsprada-bluedress.jpg",
             accessories="printed scarf, tote bag"),
        dict(scene_label="After-hours edge", designer="Patricia Field", era_decade="2000s",
             description="A cropped leather jacket, skinny jeans, and knee-high boots — Andy fully fluent in the fashion world's off-duty uniform.",
             colors=["black", "rust"], materials=["leather", "denim"], image_file="andy-devilwearsprada-leather.jpg",
             accessories="crossbody satchel"),
        dict(scene_label="Office hallway shift dress", designer="Patricia Field", era_decade="2000s",
             description="A black shift dress with a crisp white collar and a strand of pearls, styled by Nigel for Andy's first real day looking the part.",
             colors=["black", "ivory"], materials=["cotton", "silk"], image_file="annehathaway-devilwearsprada-blackmini.jpg",
             accessories="pearl necklace"),
    ]),
    ("The Devil Wears Prada", 2006, "David Frankel", "fashion-world", "Emily Charlton", [
        dict(scene_label="Senior assistant, on the phone", designer="Patricia Field", era_decade="2000s",
             description="A structured black top with an asymmetric ruffled collar and a chain-and-stud belt — Emily's armor for surviving the Elias-Clark hallways.",
             colors=["black", "grey"], materials=["wool", "leather"], image_file="emilyblunt-devilwearsprada-black.jpg",
             accessories="layered chain necklace"),
    ]),
    ("Breakfast at Tiffany's", 1961, "Blake Edwards", "fashion-world", "Holly Golightly", [
        dict(scene_label="Fifth Avenue window-shopping", designer="Hubert de Givenchy", era_decade="1960s",
             description="The little black dress and pearls that became one of the most referenced silhouettes in film costume history.",
             colors=["black", "silver"], materials=["silk"],
             image_url="https://tomandlorenzo.com/wp-content/uploads/2020/07/One-Iconic-Look-Audrey-Hepburn-Breakfast-At-Tiffanys-Costumes-Movies-Fashion-Givenchy-Tom-Lorenzo-Site-17.jpg",
             accessories="pearl necklace, opera-length gloves"),
    ]),
    ("Beetlejuice", 1988, "Tim Burton", "horror", "Lydia Deetz", [
        dict(scene_label="Wedding/sacrifice dress", designer="Aggie Guerard Rodgers", era_decade="1980s",
             description="A red gothic wedding gown that fuses bridal tradition with horror-movie dread.",
             colors=["red", "black"], materials=["tulle", "lace"], image_file="lydiadeetz-beetlejuice-reddress.webp"),
    ]),
    ("The Addams Family", 1991, "Barry Sonnenfeld", "horror", "Morticia Addams", [
        dict(scene_label="Family portrait look", designer="Ruth Myers", era_decade="n/a",
             description="The severe black silhouette with tendril-like hem, elegant and unmistakably gothic.",
             colors=["black", "green"], materials=["velvet"], image_file="morticia-addamsfamily.jpg"),
    ]),
    ("Moulin Rouge!", 2001, "Baz Luhrmann", "fashion-world", "Satine", [
        dict(scene_label="Diamond stage number", designer="Catherine Martin", era_decade="1900s",
             description="A gold sequined bodysuit with a sweeping white ostrich-feather train — Satine's entrance on the trapeze, swinging into the film's most famous number.",
             colors=["gold", "white"], materials=["sequin", "satin"], image_file="satine-moulinrouge-diamondgown.jpeg"),
    ]),
    ("Frankenstein", 2025, "Guillermo del Toro", "horror", "Elizabeth Lavenza", [
        dict(scene_label="Debut introduction gown", designer="Kate Hawley", era_decade="1850s",
             description="A turquoise-and-gold gown paired with an iridescent beetle-inspired necklace, introducing Elizabeth's insect motif in her first scene.",
             colors=["turquoise", "green", "gold"], materials=["silk", "brocade"], image_file="elizabeth-frankenstein-tealruffles.jpg",
             accessories="beetle-motif necklace, feathered headpiece"),
        dict(scene_label="Sheer nightgown, staircase scene", designer="Kate Hawley", era_decade="1850s",
             description="A translucent ivory nightgown worn in a candlelit descent down a staircase, a classic gothic-romance visual moment.",
             colors=["ivory", "gold"], materials=["lace", "silk"], image_file="elizabeth-frankenstein-whitenightgown.jpg",
             accessories="candelabra"),
        dict(scene_label="Final bride look", designer="Kate Hawley", era_decade="1850s",
             description="A bone-white gown with bandage-like textures and an exposed-ribcage motif, deliberately echoing the Creature's design.",
             colors=["white", "silver"], materials=["lace", "silk"], image_file="elizabeth-frankenstein-bridal.jpg"),
        dict(scene_label="Bistro / day dress", designer="Kate Hawley", era_decade="1850s",
             description="Custom-woven malachite-green silk with marbled velvet detailing, giving Elizabeth a luminous, almost otherworldly quality.",
             colors=["green", "gold"], materials=["silk", "velvet"], image_file="elizabeth-frankenstein-forestgreen.jpg",
             accessories="veiled bonnet"),
    ]),
    ("Portrait of a Lady on Fire", 2019, "Céline Sciamma", "period-drama", "Marianne", [
        dict(scene_label="Coastal walk, red dress", designer="Dorothée Guiraud", era_decade="1770s",
             description="A single, stripped-down maroon dress and coat that anchors Marianne's look throughout the film, following the director's one-outfit-per-character concept.",
             colors=["burgundy"], materials=["wool", "linen"], image_file="marianne-portraitofalady-maroon.jpg"),
    ]),
    ("The Favourite", 2018, "Yorgos Lanthimos", "period-drama", "Sarah Churchill", [
        dict(scene_label="Palace hunting look", designer="Sandy Powell", era_decade="1700s",
             description="A severe black-and-white silhouette — lace-trimmed coat, tricorn hat, and a pistol raised mid-hunt — blending period tailoring with a modern, almost punk sensibility.",
             colors=["black", "white"], materials=["wool", "leather"], image_file="sarahchurchill-thefavourite-huntinglook.jpg",
             accessories="tricorn hat, pistol"),
    ]),
    ("Little Women", 2019, "Greta Gerwig", "period-drama", "Jo March", [
        dict(scene_label="Writing-desk attic scene", designer="Jacqueline Durran", era_decade="1860s",
             description="A forest-green jacket over a practical dress, worn writing at her desk — reflecting Jo's independence and disinterest in the fashionable expectations placed on her sisters.",
             colors=["green", "khaki"], materials=["wool", "cotton"], image_file="jomarch-littlewomen-greenjacket.jpg"),
    ]),
    ("Little Women", 2019, "Greta Gerwig", "period-drama", "Amy March", [
        dict(scene_label="Attic sketching, blue cape", designer="Jacqueline Durran", era_decade="1860s",
             description="A powder-blue wool cape over a matching dress — Amy's quieter, more refined counterpoint to Jo's rust-toned practicality.",
             colors=["blue"], materials=["wool"], image_file="florencepugh-littlewomen-bluecvape.jpg",
             accessories="tasseled rosary"),
    ]),
    ("Dune", 2021, "Denis Villeneuve", "sci-fi", "Chani", [
        dict(scene_label="Fremen stillsuit", designer="Jacqueline West", era_decade="n/a",
             description="A functional desert stillsuit in weathered grey armor plating with a khaki desert scarf, built to evoke the rock and dust of Arrakis, designed with co-costume designer Bob Morgan.",
             colors=["khaki", "grey"], materials=["leather", "cotton"], image_file="chani-dune-stillsuit.avif"),
    ]),
    ("The Lord of the Rings: The Fellowship of the Ring", 2001, "Peter Jackson", "sci-fi", "Galadriel", [
        dict(scene_label="Mirror of Galadriel scene", designer="Ngila Dickson", era_decade="n/a",
             description="A flowing white-and-gold gown that gives the Elven queen an otherworldly, almost luminous presence.",
             colors=["white", "gold", "silver"], materials=["silk", "organza"],
             image_url="https://static.wikia.nocookie.net/lotr/images/c/cb/Galadriel.jpg/revision/latest"),
    ]),
    ("Cruella", 2021, "Craig Gillespie", "fashion-world", "Cruella de Vil", [
        dict(scene_label="Runway crash entrance", designer="Jenny Beavan", era_decade="1970s",
             description="A dramatic black-and-white couture gown built for a grand entrance, fusing punk attitude with high fashion.",
             colors=["black", "white", "red"], materials=["tulle", "satin"], image_file="emmastone-cruella-redblack.jpg",
             accessories="sculptural headpiece, gold chain jewelry"),
        dict(scene_label="Fireside red gown", designer="Jenny Beavan", era_decade="1970s",
             description="A structured crimson gown with a dramatic train, worn for a quieter, more calculating moment by the fire.",
             colors=["red"], materials=["velvet", "satin"], image_file="emmastone-cruella-red.jpg"),
    ]),
    ("House of Gucci", 2021, "Ridley Scott", "fashion-world", "Patrizia Reggiani", [
        dict(scene_label="Low-cut red evening dress", designer="Janty Yates", era_decade="1970s",
             description="A daringly cut red dress altered on set for more leg, worn to a masquerade party — part of Patrizia's rise into the world of Italian luxury fashion.",
             colors=["red"], materials=["satin", "silk"], image_file="patrizia-houseofgucci-reddress.jpg"),
    ]),
    ("Crimson Peak", 2015, "Guillermo del Toro", "horror", "Edith Cushing", [
        dict(scene_label="Allerdale Hall arrival", designer="Kate Hawley", era_decade="1900s",
             description="A deep crimson ruffled gown with a dramatic train, worn at the piano in Allerdale Hall — another del Toro/Hawley collaboration built around the mansion's blood-red clay.",
             colors=["burgundy"], materials=["velvet", "lace"], image_file="edithcushing-crimsonpeak-piano.jpeg"),
    ]),
    ("Suspiria", 2018, "Luca Guadagnino", "horror", "Susie Bannion", [
        dict(scene_label="Dance academy rehearsal leotard", designer="Giulia Piersanti", era_decade="1970s",
             description="A white leotard with a black waist belt, worn at the ballet barre during rehearsal — a rare moment of stillness in the film's otherwise muted, foreboding palette.",
             colors=["white", "black"], materials=["cotton"], image_file="susiebannion-suspiria-whiteleotard.jpeg"),
    ]),
    ("Mr. & Mrs. Smith", 2005, "Doug Liman", "action", "Jane Smith", [
        dict(scene_label="Cocktail black dress, poster look", designer="", era_decade="2000s",
             description="A fitted black cocktail dress slit to the thigh, holstered weapon included — the film's iconic double-exposure poster image.",
             colors=["black"], materials=["satin"], image_file="angelina-mrandmrssmith-cover-blackdress.jpg",
             accessories="thigh holster"),
        dict(scene_label="Post-explosion white shirt", designer="", era_decade="2000s",
             description="An oversized white shirt and red rain boots, worn walking away from a house leveled in a shootout — glamour as deadpan punchline.",
             colors=["white", "red"], materials=["cotton", "leather"], image_file="angelina-mrandmrssmith-oversizedwhiteshirt.jpg",
             accessories="red rubber rain boots"),
    ]),
    ("Ocean's 8", 2018, "Gary Ross", "heist", "Daphne Kluger", [
        dict(scene_label="Met Gala centerpiece gown", designer="Sarah Edwards", era_decade="2010s",
             description="A fuchsia off-shoulder gown paired with a diamond necklace worth the entire heist — Daphne playing the mark and the spectacle at once.",
             colors=["pink"], materials=["satin", "tulle"], image_file="annehathaway-oceans8-pinkgown.jpg",
             accessories="diamond statement necklace"),
    ]),
    ("Ocean's 8", 2018, "Gary Ross", "heist", "Nine Ball", [
        dict(scene_label="Met Gala staircase entrance", designer="Sarah Edwards", era_decade="2010s",
             description="A structured red mermaid gown worn descending the Met steps mid-heist — cool nerve dressed as red-carpet glamour.",
             colors=["red"], materials=["satin", "sequin"], image_file="rihanna-oceans8-redgown.jpg",
             accessories="beaded arm gauntlet"),
    ]),
    ("Ocean's 8", 2018, "Gary Ross", "heist", "Debbie Ocean", [
        dict(scene_label="One-shoulder gold-beaded gown", designer="Sarah Edwards", era_decade="2010s",
             description="A sheer, gold-embroidered gown worn as the crew's mastermind finally gets her night at the Gala she planned all along.",
             colors=["gold", "black"], materials=["silk", "sequin"], image_file="sandrabullock-oceans8-crystal.jpg"),
    ]),
    ("The Princess Diaries", 2001, "Garry Marshall", "coming-of-age", "Mia Thermopolis", [
        dict(scene_label="Coronation ball gown", designer="", era_decade="2000s",
             description="An ivory gown embroidered with gold florals, worn with a tiara for Mia's formal introduction as Princess of Genovia.",
             colors=["ivory", "gold"], materials=["satin", "lace"], image_file="annehathaway-princessdiaries-ballgown.jpg",
             accessories="diamond tiara"),
    ]),
    ("Barbie", 2023, "Greta Gerwig", "comedy", "Barbie", [
        dict(scene_label="Beach day sailor set", designer="Jacqueline Durran", era_decade="n/a",
             description="A striped halter top and shorts with a nautical wheel belt buckle — Barbie's default, endlessly cheerful beach uniform.",
             colors=["blue", "white"], materials=["cotton"], image_file="barbie-bluewhite-sailor.jpg",
             accessories="sunglasses, gold hoop earrings"),
        dict(scene_label="Pink cowgirl western wear", designer="Jacqueline Durran", era_decade="n/a",
             description="A magenta denim vest-and-pants set with a paisley bandana, worn riding into the real world.",
             colors=["pink"], materials=["denim"], image_file="barbie-pinkdenim.jpg",
             accessories="white cowboy hat, paisley bandana"),
        dict(scene_label="Gingham pool dress", designer="Jacqueline Durran", era_decade="n/a",
             description="The pink-and-white gingham sundress that became the film's signature silhouette, worn by the pool in Barbieland.",
             colors=["pastel-pink", "white"], materials=["cotton"], image_file="barbie-pinkgingham.jpg",
             accessories="flower charm necklace"),
        dict(scene_label="Disco sequin jumpsuit", designer="Jacqueline Durran", era_decade="n/a",
             description="An iridescent sequined jumpsuit, dance-floor ready, catching every color in the room.",
             colors=["silver", "pink"], materials=["sequin"], image_file="barbie-sparkle-jumpsuit.jpg",
             accessories="statement bracelet"),
        dict(scene_label="Striped swim romper", designer="Jacqueline Durran", era_decade="n/a",
             description="A black-and-white striped one-piece — a direct nod to the original 1959 Barbie doll's debut swimsuit.",
             colors=["black", "white"], materials=["cotton"], image_file="barbie-striped-romper.jpg",
             accessories="cat-eye sunglasses"),
        dict(scene_label="Yellow tweed press suit", designer="Jacqueline Durran", era_decade="n/a",
             description="A pastel tweed skirt suit with a bell-sleeve blouse and gold chain belt, worn on Barbie's press tour through the real world.",
             colors=["gold", "pastel-pink"], materials=["tweed", "silk"], image_file="barbie-yellowplaid.jpg",
             accessories="pearl drop earrings, gold chain belt"),
        dict(scene_label="Real-world collared dress", designer="Jacqueline Durran", era_decade="n/a",
             description="A cobalt-blue dress with a crisp white Peter Pan collar, worn as Barbie steps into the real world for the first time.",
             colors=["blue", "white"], materials=["cotton"], image_file="barbie-realworld-bluecollareddress.jpeg",
             accessories="white drop earrings"),
    ]),
    ("Clueless", 1995, "Amy Heckerling", "comedy", "Cher Horowitz", [
        dict(scene_label="Yellow plaid schoolgirl suit", designer="Mona May", era_decade="1990s",
             description="The matching yellow plaid blazer and pleated skirt that defined '90s teen style — Beverly Hills prep as its own uniform.",
             colors=["gold"], materials=["wool", "tweed"], image_file="cher-clueless-plaidyellowsuit.jpg",
             accessories="white knee socks"),
    ]),
    ("Clueless", 1995, "Amy Heckerling", "comedy", "Dionne Davenport", [
        dict(scene_label="Poolside velvet mini dress", designer="Mona May", era_decade="1990s",
             description="A ruby velvet mini dress with a white Peter Pan collar and matching over-the-knee socks — Dionne's polished counterpoint to Cher's plaid.",
             colors=["red"], materials=["velvet"], image_file="dionne-clueless-rubyvelvet.jpg",
             accessories="white opera gloves, headband"),
    ]),
    ("Enchanted", 2007, "Kevin Lima", "fantasy", "Giselle", [
        dict(scene_label="Curtain-fabric gown", designer="", era_decade="2000s",
             description="A gown Giselle stitches from a New York apartment's curtains, embroidered by hand with woodland creatures — animated fairy-tale habits colliding with the real world.",
             colors=["turquoise", "pink"], materials=["velvet", "brocade"], image_file="giselle-enchanted-curtaindress.jpg",
             accessories="flowers in hair"),
        dict(scene_label="Runaway wedding gown", designer="", era_decade="2000s",
             description="A voluminous ivory ball gown with puffed sleeves, worn to a wedding Giselle ultimately walks away from.",
             colors=["ivory"], materials=["tulle", "satin"], image_file="giselle-enchanted-weddinggown.jpg",
             accessories="bridal tiara"),
    ]),
    ("Legally Blonde", 2001, "Robert Luketic", "comedy", "Elle Woods", [
        dict(scene_label="Courtroom pink power suit", designer="", era_decade="2000s",
             description="A coral-pink wrap dress worn to cross-examine a witness and win a murder trial — pink as a legal strategy.",
             colors=["pink"], materials=["satin"], image_file="elle-legallyblonde-pink-courtroomsuit.jpg",
             accessories="pink tote bag"),
    ]),
    ("Me Before You", 2016, "Thea Sharrock", "romance", "Louisa Clark", [
        dict(scene_label="Bumblebee tights", designer="", era_decade="2010s",
             description="Striped bumblebee tights under a pleated navy skirt — Louisa's determinedly bright, slightly eccentric personal uniform.",
             colors=["navy", "gold"], materials=["wool", "cotton"], image_file="emilia-mebeforeyou-bumblebeetights.jpg",
             accessories="crossbody bag"),
        dict(scene_label="Red dress, staircase", designer="", era_decade="2010s",
             description="A simple red fit-and-flare dress worn for one of the film's pivotal quiet moments.",
             colors=["red"], materials=["cotton", "satin"], image_file="emiliaclarke-mebeforeyou-redgown.jpg",
             accessories="printed silk scarf"),
    ]),
    ("Mean Girls", 2004, "Mark Waters", "comedy", "Regina George", [
        dict(scene_label="Off-shoulder black sweater", designer="", era_decade="2000s",
             description="An off-the-shoulder black sweater over low-rise jeans — Plastics-approved casual wear.",
             colors=["black"], materials=["wool", "denim"], image_file="regina-meangirls-black-offshoulder.jpg"),
        dict(scene_label="Mall floral halter", designer="", era_decade="2000s",
             description="A bright floral halter top worn on a mall trip — peak mid-2000s junior fashion.",
             colors=["pink"], materials=["cotton"], image_file="regina-meangirls-floraltank.jpg",
             accessories="pink shoulder bag"),
    ]),
    ("Enola Holmes", 2020, "Harry Bradbeer", "period-drama", "Enola Holmes", [
        dict(scene_label="Crimson traveling gown", designer="Consolata Boyle", era_decade="1880s",
             description="A deep red bustled traveling dress worn while investigating alone in London — practical enough to run in, striking enough to be remembered.",
             colors=["burgundy"], materials=["wool", "cotton"], image_file="enolaholmes-crimsongown.jpg"),
    ]),
    ("Wicked", 2024, "Jon M. Chu", "musical", "Glinda", [
        dict(scene_label="Behind-the-scenes ruffled robe", designer="Paul Tazewell", era_decade="n/a",
             description="A rose-pink tulle robe with sculptural sleeve ruffles, worn between scenes at Shiz.",
             colors=["pink"], materials=["tulle"], image_file="glinda-wicked-pinknet.jpg"),
        dict(scene_label="‘Popular’ entrance gown", designer="Paul Tazewell", era_decade="n/a",
             description="The iridescent pink ballgown and tiara for Glinda's signature bubble entrance.",
             colors=["pastel-pink"], materials=["tulle", "satin"], image_file="glinda-wicked-pinkruffles.jpg",
             accessories="tiara, sparkling wand"),
        dict(scene_label="Travel skirt suit", designer="Paul Tazewell", era_decade="n/a",
             description="A striped pink skirt suit with a small feathered hat, worn arriving at Shiz University.",
             colors=["pastel-pink", "silver"], materials=["wool", "tweed"], image_file="glinda-wicked-skirtsuit.jpg",
             accessories="feathered travel hat"),
    ]),
    ("13 Going on 30", 2004, "Gary Winick", "comedy", "Jenna Rink", [
        dict(scene_label="Razzle Dazzle mosaic dress", designer="", era_decade="2000s",
             description="A color-blocked silk dress worn to lead an entire office party through a spontaneous 'Thriller' dance number.",
             colors=["green", "purple", "turquoise"], materials=["silk"], image_file="jennifer-13goingon30-mosaicdress.jpg",
             brand="Versace"),
        dict(scene_label="White biker jacket", designer="", era_decade="2000s",
             description="A cream leather jacket worn window-shopping through New York, freshly transported into her 30-year-old life.",
             colors=["ivory", "khaki"], materials=["leather"], image_file="jennifer-13goingon30-whitebikerjacket.jpg",
             accessories="spiked hair pins"),
        dict(scene_label="Crimson skirt, courthouse steps", designer="", era_decade="2000s",
             description="A cream ribbed sweater over a satin crimson pleated skirt, worn holding a bouquet on the courthouse steps.",
             colors=["ivory", "burgundy"], materials=["cotton", "satin"], image_file="jennarink-13goingon30-crimsonskirt.jpg"),
    ]),
    ("Pretty Woman", 1990, "Garry Marshall", "romance", "Vivian Ward", [
        dict(scene_label="Brown polka-dot day dress", designer="Marilyn Vance", era_decade="1990s",
             description="A brown-and-white polka dot dress worn to the polo match — Vivian's first fully successful pass at old-money dressing.",
             colors=["khaki"], materials=["cotton"], image_file="juliaroberts-prettywoman-brownpolka.jpg",
             accessories="wide-brim hat, white gloves"),
    ]),
    ("How to Lose a Guy in 10 Days", 2003, "Donald Petrie", "romance", "Andie Anderson", [
        dict(scene_label="Butter-yellow satin gown", designer="", era_decade="2000s",
             description="A bias-cut yellow satin gown worn to a black-tie diamond event — full old-Hollywood glamour.",
             colors=["gold"], materials=["satin"], image_file="katehudson-howtoloseaguy-butteryellowgown.jpg",
             accessories="white satin clutch"),
        dict(scene_label="White eyelet skirt, pier scene", designer="", era_decade="2000s",
             description="A strapless white top and an embroidered white eyelet skirt, worn on the waterfront in the film's early courtship scenes.",
             colors=["white"], materials=["cotton"], image_file="andieanderson-howtoloseaguy-whitestrapless.jpg",
             accessories="black crossbody bag, pearl earrings"),
        dict(scene_label="Grey wrap dress, scooter ride", designer="", era_decade="2000s",
             description="A grey wrap dress worn racing through the city on a scooter, bike helmet and all.",
             colors=["grey"], materials=["silk"], image_file="andieanderson-howtoloseaguy-greyhalter.jpg",
             accessories="bike helmet"),
    ]),
    ("Atonement", 2007, "Joe Wright", "period-drama", "Cecilia Tallis", [
        dict(scene_label="Emerald green backless gown", designer="Jacqueline Durran", era_decade="1930s",
             description="The bias-cut emerald silk gown from the library scene — one of the most referenced dresses in modern costume design.",
             colors=["green"], materials=["silk"], image_file="keira-atonement-greendress.jpg"),
        dict(scene_label="Floral tea gown", designer="Jacqueline Durran", era_decade="1930s",
             description="A sheer floral blouse and striped skirt worn in the garden before the family dinner that changes everything.",
             colors=["khaki", "pink"], materials=["chiffon", "cotton"], image_file="keira-atonement-floral.jpg",
             accessories="hand-picked flower bouquet"),
        dict(scene_label="Fountain slip", designer="Jacqueline Durran", era_decade="1930s",
             description="A pale silk slip, soaked through after Cecilia dives into the fountain to retrieve a broken piece of a vase — one of the film's defining images.",
             colors=["ivory"], materials=["silk"], image_file="keira-atonement-fountainslip.jpg"),
    ]),
    ("Cinderella", 2015, "Kenneth Branagh", "fantasy", "Cinderella", [
        dict(scene_label="Ball gown, grand staircase", designer="Sandy Powell", era_decade="n/a",
             description="A cornflower-blue silk-organza gown, famously built from thousands of crystals and yards of tulle, worn descending the palace stairs.",
             colors=["blue"], materials=["organza", "tulle"], image_file="lilyjames-cinderella-gown.jpg",
             accessories="glass slippers"),
    ]),
    ("La La Land", 2016, "Damien Chazelle", "musical", "Mia Dolan", [
        dict(scene_label="Purple dress, dance rehearsal", designer="Mary Zophres", era_decade="2010s",
             description="A deep plum halter dress worn twirling against a painted hillside backdrop during 'A Lovely Night.'",
             colors=["purple"], materials=["satin"], image_file="mia-lalaland-purple.jpg"),
        dict(scene_label="Cobalt party dress", designer="Mary Zophres", era_decade="2010s",
             description="A cobalt-blue chiffon dress worn to a Hollywood Hills party, one of the film's brightest, most saturated color notes.",
             colors=["blue"], materials=["chiffon"], image_file="mia-lalaland-royalblue.jpg"),
        dict(scene_label="Yellow dress, city overlook", designer="Mary Zophres", era_decade="2010s",
             description="The canary-yellow dress from the film's most-referenced promotional image, worn overlooking the city at dusk.",
             colors=["gold"], materials=["chiffon", "cotton"], image_file="mia-lalaland-yellowdress.jpg"),
    ]),
    ("The Notebook", 2004, "Nick Cassavetes", "romance", "Allie Hamilton", [
        dict(scene_label="Rowboat blue dress", designer="", era_decade="1940s",
             description="A simple sky-blue day dress worn on a rowboat date among the swans — one of the film's quieter, most iconic images.",
             colors=["blue"], materials=["cotton"], image_file="rachel-notebook-babyblue.jpg"),
        dict(scene_label="Burgundy garden party dress", designer="", era_decade="1940s",
             description="A burgundy dress with a matching flower-trimmed hat, worn to a formal garden engagement party.",
             colors=["burgundy"], materials=["cotton", "wool"], image_file="rachel-notebook-burgundy.jpg",
             accessories="flower-trimmed hat"),
        dict(scene_label="Bandana-print sundress", designer="", era_decade="1940s",
             description="A crimson bandana-print sundress worn on a casual day out, eating ice cream by the water.",
             colors=["red"], materials=["cotton"], image_file="rachel-notebook-crimsondots.jpg"),
    ]),
    ("The Other Boleyn Girl", 2008, "Justin Chadwick", "period-drama", "Anne Boleyn", [
        dict(scene_label="Sage and gold damask gown", designer="", era_decade="1520s",
             description="A sage-green and gold brocade gown with a jeweled French hood, worn at court as Anne begins to catch the King's eye.",
             colors=["green", "gold"], materials=["damask", "brocade"], image_file="natalie-anneboleyn-sagegown.jpg",
             accessories="jeweled French hood, pearl necklace"),
    ]),
    ("Titanic", 1997, "James Cameron", "period-drama", "Rose DeWitt Bukater", [
        dict(scene_label="First-class dinner gown", designer="Deborah Lynn Scott", era_decade="1910s",
             description="A beaded burgundy chiffon gown worn to Rose's first dinner aboard the Titanic, laced into a corset and a life she's already outgrown.",
             colors=["burgundy", "black"], materials=["chiffon", "satin"], image_file="rose-titanic-diningown.jpg",
             accessories="pearl choker"),
    ]),
    ("Ready or Not", 2019, "Matt Bettinelli-Olpin & Tyler Gillett", "horror", "Grace", [
        dict(scene_label="Wedding dress, shotgun in hand", designer="", era_decade="2010s",
             description="A lace wedding gown paired with a bandolier and a hunting shotgun — bridal tradition and survival horror colliding by midnight.",
             colors=["ivory"], materials=["lace"], image_file="samaraweaving-readyornot-bridal.jpg",
             accessories="bullet bandolier, hunting shotgun"),
    ]),
    ("27 Dresses", 2008, "Anne Fletcher", "romance", "Jane Nichols", [
        dict(scene_label="Grey-lavender halter gown, brownstone steps", designer="", era_decade="2000s",
             description="A grey-lavender satin halter gown with a sash, worn leaving a wedding on a New York brownstone stoop, flowers in hand.",
             colors=["silver", "purple"], materials=["satin"], image_file="janenichols-27dresses-greybluesatin.jpg"),
        dict(scene_label="Sage green taffeta gown", designer="", era_decade="2000s",
             description="A strapless sage-green taffeta ball gown with a dropped-waist skirt — one of the many bridesmaid dresses Jane keeps in her closet.",
             colors=["green"], materials=["satin"], image_file="janenichols-27dresses-sagegreensilk.jpg"),
    ]),
    ("Black Swan", 2010, "Darren Aronofsky", "horror", "Nina Sayers", [
        dict(scene_label="Black Swan stage costume", designer="Amy Westcott", era_decade="2010s",
             description="A feathered black tutu and beaded corset bodice worn for Nina's final, transformative performance as the Black Swan.",
             colors=["black"], materials=["tulle", "sequin"], image_file="ninasayers-blackswan-glamour.webp",
             accessories="crystal tiara, dramatic eye makeup"),
    ]),
    ("Masters of the Universe", 2026, "", "fantasy", "Teela", [
        dict(scene_label="Eternian warrior armor", designer="", era_decade="n/a",
             description="A gold-and-white leather armor set with cracked-metal texturing and reinforced arm cuffs, built for battle on Eternia.",
             colors=["gold", "white"], materials=["leather"], image_file="teela-mastersoftheuniverse-armor.webp",
             accessories="leather thigh holster, arm cuffs"),
    ]),
    ("Gone with the Wind", 1939, "Victor Fleming", "period-drama", "Scarlett O'Hara", [
        dict(scene_label="Red velvet Christmas gown", designer="Walter Plunkett", era_decade="1860s",
             description="A deep red velvet gown with a feathered, jeweled bodice and tulle wrap — one of Scarlett's most opulent looks in the film.",
             colors=["red"], materials=["velvet", "tulle"], image_file="scarlett-gonewiththewind-redgown.webp"),
    ]),
    ("Black Panther: Wakanda Forever", 2022, "Ryan Coogler", "sci-fi", "Queen Ramonda", [
        dict(scene_label="Coronation purple gown", designer="Ruth E. Carter", era_decade="n/a",
             description="A deep purple velvet gown with a sheer ombre cape and gold Wakandan-inspired embroidery, worn for a formal court appearance.",
             colors=["purple", "gold"], materials=["velvet", "tulle"], image_file="ramonda-blackpanther-purplevelvet.webp",
             accessories="beaded headwrap, gold jewelry"),
        dict(scene_label="Mourning gown, patterned skirt", designer="Ruth E. Carter", era_decade="n/a",
             description="A structured black gown with an intricately patterned full skirt and sculptural headwrap, worn during a period of mourning.",
             colors=["black"], materials=["brocade"], image_file="ramonda-blackpanther-funeraldress.jpeg",
             accessories="sculptural headwrap, statement necklace"),
        dict(scene_label="Ivory beaded gown, lace cape", designer="Ruth E. Carter", era_decade="n/a",
             description="An ivory beaded gown with a lace capelet and a woven headpiece, displayed as part of the film's formal Wakandan royal wardrobe.",
             colors=["ivory"], materials=["lace", "sequin"], image_file="ramonda-blackpanther-ivorygown.jpg"),
    ]),
    ("Uptown Girls", 2003, "Boaz Yakin", "comedy", "Molly Gunn", [
        dict(scene_label="Sequined party gown", designer="", era_decade="2000s",
             description="A pastel sequined slip gown with floral embroidery, worn to a birthday party in one of Molly's more glamorous moments.",
             colors=["pastel-pink", "turquoise"], materials=["sequin"], image_file="mollygunn-uptowngirls-sequins.jpg"),
        dict(scene_label="Hand-embroidered denim overalls", designer="", era_decade="2000s",
             description="A denim overall dress covered in hand-sewn floral and butterfly patches — thrifted-eccentric, entirely Molly's own style.",
             colors=["blue"], materials=["denim"], image_file="mollygunn-uptowngirls-denimoveralls.jpg",
             accessories="orange crossbody bag"),
        dict(scene_label="Lilac tank and striped midi skirt", designer="", era_decade="2000s",
             description="A lilac tank top under a cream cardigan with a soft striped chiffon midi skirt, worn on a walk through the city.",
             colors=["purple", "khaki"], materials=["chiffon", "cotton"], image_file="mollygunn-uptowngirls-lilactank.jpg"),
    ]),
    ("The Mask", 1994, "Chuck Russell", "comedy", "Tina Carlyle", [
        dict(scene_label="Red slip dress, office lobby", designer="", era_decade="1990s",
             description="A fitted red slip dress slit to the thigh, worn in Tina's first, show-stopping entrance into the film.",
             colors=["red"], materials=["satin"], image_file="tinacarlyle-themask-redslipdress.webp",
             accessories="delicate gold necklace"),
    ]),
    ("The Marvels", 2023, "Nia DaCosta", "sci-fi", "Carol Danvers", [
        dict(scene_label="Gala gown, star motif", designer="", era_decade="n/a",
             description="A deep red and navy gown with a sculptural gold star at the bodice and waist — Carol's Captain Marvel emblem reimagined as formalwear.",
             colors=["burgundy", "navy"], materials=["chiffon"], image_file="carolwanvers-themarvels-galadress.jpg",
             accessories="gold star necklace"),
    ]),
    ("The Aviator", 2004, "Martin Scorsese", "period-drama", "Katharine Hepburn", [
        dict(scene_label="Red plaid blazer and trousers", designer="Sandy Powell", era_decade="1940s",
             description="A red-and-black plaid wool blazer over trousers — the kind of confident, masculine-cut tailoring Hepburn was known for off-screen too.",
             colors=["burgundy", "black"], materials=["wool"], image_file="katharinehepburn-aviator-redplaid.webp"),
    ]),
    ("Confessions of a Shopaholic", 2009, "P.J. Hogan", "comedy", "Rebecca Bloomwood", [
        dict(scene_label="Plaid cape coat, statement bags", designer="", era_decade="2000s",
             description="A multicolor plaid cape coat worn over a cobalt dress, piled with mismatched statement handbags — Rebecca's shopping-addiction wardrobe in one look.",
             colors=["purple", "gold", "green"], materials=["wool", "leather"], image_file="rebeccabloomwood-shopaholic-plaidcoat.jpg",
             accessories="orange leather gloves, green silk scarf, multiple handbags"),
    ]),
    ("Crazy Rich Asians", 2018, "Jon M. Chu", "romance", "Astrid Leong", [
        dict(scene_label="Ice-blue floral-appliqué gown", designer="Mary E. Vogt", era_decade="2010s",
             description="A pale ice-blue tulle gown with floral appliqué at the shoulders and waist and a deep V neckline, worn to a wedding as one of the film's quieter, more restrained looks.",
             colors=["blue"], materials=["tulle"], image_file="gemmachan-crazyrichasians-icebluetulle.jpeg"),
    ]),
    ("Crazy Rich Asians", 2018, "Jon M. Chu", "romance", "Rachel Chu", [
        dict(scene_label="Gold sequined wedding gown", designer="Mary E. Vogt", era_decade="2010s",
             description="A gold sequined gown with a tiered high-low skirt and cathedral veil, worn walking down an aisle flooded ankle-deep in water.",
             colors=["gold", "ivory"], materials=["sequin", "tulle"], image_file="rachelchu-crazyrichasians-goldbridal.jpg",
             accessories="cathedral veil, orchid bouquet"),
    ]),
    ("Crazy Rich Asians", 2018, "Jon M. Chu", "romance", "Eleanor Young", [
        dict(scene_label="White pinstripe suit", designer="Mary E. Vogt", era_decade="2010s",
             description="A crisp white pinstripe suit worn walking through a Singapore shophouse arcade — quiet, controlled authority.",
             colors=["white", "navy"], materials=["wool"], image_file="eleanoryoung-crazyrichasians-whitepinstripe.webp",
             accessories="dark sunglasses"),
        dict(scene_label="Blue and silver beaded gown", designer="Mary E. Vogt", era_decade="2010s",
             description="A pale blue beaded gown with a silver wrap stole, worn to the wedding gala — old-money glamour with lace detailing throughout.",
             colors=["blue", "silver"], materials=["lace", "sequin"], image_file="eleanoryoung-crazyrichasians-bluebeaded.jpg",
             accessories="drop earrings, statement belt buckle"),
    ]),
    ("Nosferatu", 2024, "Robert Eggers", "horror", "Ellen Hutter", [
        dict(scene_label="Floral day dress, bouquet", designer="Linda Muir", era_decade="1830s",
             description="A sage-green floral Victorian day dress worn while holding a bouquet of dried lilacs — a rare moment of stillness before the film's dread sets in.",
             colors=["green", "purple"], materials=["cotton"], image_file="ellenhutter-nosferatu-floraldress.avif"),
        dict(scene_label="Mourning gown and bonnet", designer="Linda Muir", era_decade="1830s",
             description="A black mourning gown with a wide bonnet and full cape sleeves, worn walking through a graveyard.",
             colors=["black"], materials=["velvet"], image_file="ellenhutter-nosferatu-mourninggown.webp",
             accessories="black lace bonnet"),
    ]),
    ("The Wizard of Oz", 1939, "Victor Fleming", "fantasy", "Glinda the Good Witch", [
        dict(scene_label="Pink bubble gown, crown, and wand", designer="Adrian", era_decade="n/a",
             description="A pale pink tulle ballgown covered in star appliqués, paired with a crystal crown and star wand — the archetype for every good witch since.",
             colors=["pastel-pink"], materials=["tulle", "sequin"], image_file="glinda-wizardofoz-pinkgown.avif",
             accessories="crystal crown, star wand"),
    ]),
    ("Iron Man", 2008, "Jon Favreau", "sci-fi", "Pepper Potts", [
        dict(scene_label="White skirt suit, Stark Industries", designer="", era_decade="2000s",
             description="A tailored white skirt suit worn walking the halls of Stark Industries — buttoned-up, efficient, unmistakably Pepper.",
             colors=["white"], materials=["wool"], image_file="pepperpotts-ironman-whitesuit.jpg"),
    ]),
    ("Iron Man 2", 2010, "Jon Favreau", "sci-fi", "Pepper Potts", [
        dict(scene_label="Royal blue satin gown, gala", designer="", era_decade="2010s",
             description="A backless royal-blue satin gown worn to a Stark Expo gala — Pepper's rare, full glamour moment.",
             colors=["navy"], materials=["satin"], image_file="pepperpotts-ironman2-bluesatin.jpg"),
    ]),
    ("Anna Karenina", 2012, "Joe Wright", "period-drama", "Anna Karenina", [
        dict(scene_label="Fur-trimmed velvet coat and feathered hat", designer="Jacqueline Durran", era_decade="1870s",
             description="A gold-embroidered black velvet coat with a voluminous fox fur collar and a feathered hat, part of the film's deliberately theatrical, stage-inspired costuming.",
             colors=["black", "purple"], materials=["velvet", "fur"], image_file="annakarenina-furtrimmedcoat.webp",
             accessories="feathered hat, leather gloves"),
    ]),
    ("The Lizzie McGuire Movie", 2003, "Jim Fall", "comedy", "Lizzie McGuire", [
        dict(scene_label="Metallic green pop-star finale gown", designer="", era_decade="2000s",
             description="A metallic green halter gown with a sheer train and fishnet tights, worn for Lizzie's surprise pop-star debut in the film's finale.",
             colors=["green"], materials=["satin", "sequin"], image_file="lizziemcguire-greengown.jpg",
             accessories="gold sequined boots"),
    ]),
    ("Poor Things", 2023, "Yorgos Lanthimos", "fantasy", "Felicity", [
        dict(scene_label="Blue-grey Victorian gown, garden", designer="Holly Waddington", era_decade="1880s",
             description="A structured blue-grey wool gown with oversized puffed sleeves, part of the film's exaggerated, corseted take on Victorian silhouettes.",
             colors=["blue"], materials=["wool"], image_file="felicity-poorthings-bluegown.jpg",
             accessories="leather gloves"),
    ]),
    ("The Wolf of Wall Street", 2013, "Martin Scorsese", "drama", "Naomi Lapaglia", [
        dict(scene_label="Teal halter dress", designer="Sandy Powell", era_decade="1990s",
             description="A fitted teal halter dress worn at a garden party — sleek, confident, unmistakably Naomi.",
             colors=["turquoise"], materials=["satin"], image_file="naomilapaglia-wolfofwallstreet-tealdress.jpg",
             accessories="gold hoop earrings"),
        dict(scene_label="Black sheer-panel mini dress", designer="Sandy Powell", era_decade="1990s",
             description="A black mini dress with sheer mesh panels at the shoulders and neckline, worn on a Manhattan brownstone stoop.",
             colors=["black"], materials=["velvet"], image_file="naomilapaglia-wolfofwallstreet-blackdress.webp"),
    ]),
    ("The Return", 2024, "Uberto Pasolini", "period-drama", "Penelope", [
        dict(scene_label="Grecian gown, laurel crown", designer="", era_decade="n/a",
             description="A pale blue-grey draped linen gown with a gold laurel crown, worn awaiting Odysseus's return.",
             colors=["grey", "gold"], materials=["linen", "silk"], image_file="penelope-thereturn-greciangown.webp",
             accessories="gold laurel crown"),
    ]),
    ("The Matrix", 1999, "The Wachowskis", "sci-fi", "Trinity", [
        dict(scene_label="Black leather trenchcoat", designer="Kym Barrett", era_decade="n/a",
             description="A floor-length black PVC trenchcoat and catsuit, worn mid-firefight — the silhouette that defined the film's entire visual language.",
             colors=["black"], materials=["leather"], image_file="trinity-thematrix-leathertrenchcoat.webp",
             accessories="wraparound sunglasses"),
    ]),
    ("Troy", 2004, "Wolfgang Petersen", "period-drama", "Briseis", [
        dict(scene_label="Blue-grey draped gown", designer="", era_decade="n/a",
             description="A blue-grey draped silk gown with a woven gold headpiece, worn as a priestess of Apollo before Troy's fall.",
             colors=["blue", "gold"], materials=["silk"], image_file="briseis-troy-bluesilk.webp"),
    ]),
    ("Troy", 2004, "Wolfgang Petersen", "period-drama", "Helen", [
        dict(scene_label="Ivory and gold draped gown", designer="", era_decade="n/a",
             description="An ivory and gold draped gown with a gold laurel crown, worn beneath a parasol — the face that launched a thousand ships.",
             colors=["ivory", "gold"], materials=["silk", "brocade"], image_file="helen-troy-whitegold.jpg",
             accessories="gold laurel crown, parasol"),
    ]),
    ("Alice in Wonderland", 2010, "Tim Burton", "fantasy", "The White Queen", [
        dict(scene_label="White ballgown, gold crown", designer="Colleen Atwood", era_decade="n/a",
             description="A pale, sculptural white ballgown with a beaded bodice and a gold crown — the White Queen's deliberately ethereal, otherworldly silhouette.",
             colors=["white", "gold"], materials=["satin", "lace"], image_file="whitequeen-aliceinwonderland-ballgown.jpg",
             accessories="gold crown, pearl choker"),
    ]),
    ("Showgirls", 1995, "Paul Verhoeven", "drama", "Nomi Malone", [
        dict(scene_label="Black mini dress, dressing room", designer="", era_decade="1990s",
             description="A black mini dress with gold Medusa-medallion cutout hardware at the waist and hem — a real Gianni Versace piece worn between red velvet curtains.",
             colors=["black", "gold"], materials=["wool"], image_file="nomimalone-showgirls-versaceblack.jpeg",
             brand="Versace"),
    ]),
    ("Marty Supreme", 2025, "Josh Safdie", "drama", "Kay Stone", [
        dict(scene_label="Red coat, black gloves", designer="", era_decade="1950s",
             description="A voluminous red taffeta coat worn over black opera gloves — old-Hollywood glamour against the film's ping-pong-hall grit.",
             colors=["red"], materials=["satin"], image_file="martysupreme-redcoat.jpeg",
             accessories="black opera gloves"),
    ]),
    ("Broken Embraces", 2009, "Pedro Almodóvar", "drama", "Lena", [
        dict(scene_label="Black dress, gold chain draping", designer="", era_decade="2000s",
             description="A black dress laced with cascading gold chains — one of Lena's most editorial, fashion-forward looks in the film.",
             colors=["black", "gold"], materials=["chiffon"], image_file="lena-brokenembraces-blackandgold.jpeg",
             accessories="layered gold chains"),
    ]),
    ("The Devil Wears Prada 2", 2026, "David Frankel", "fashion-world", "Amari", [
        dict(scene_label="Gray peplum office dress", designer="", era_decade="2020s",
             description="A structured charcoal-gray peplum dress with a pleated black skirt panel, worn striding through the Runway offices.",
             colors=["grey", "black"], materials=["wool"], image_file="simoneashley-devilwearsprada2-graypeplum.jpeg"),
        dict(scene_label="Cobalt latex top, sequin skirt", designer="", era_decade="2020s",
             description="A high-shine cobalt latex top over a burgundy sequined skirt, worn backstage at a fashion show.",
             colors=["blue", "burgundy"], materials=["leather", "sequin"], image_file="simoneashley-devilwearsprada2-cobaltlatex.webp"),
        dict(scene_label="Navy blazer and pleated mini skirt", designer="", era_decade="2020s",
             description="A crisp white shirt under a fitted navy blazer, paired with a pleated navy mini skirt.",
             colors=["navy"], materials=["wool"], image_file="simoneashley-devilwearsprada2-navyblazerset.jpeg"),
        dict(scene_label="Black blazer, plaid tie", designer="", era_decade="2020s",
             description="A tailored black blazer over a white shirt and plaid tie, worn in a tense office moment.",
             colors=["black", "white"], materials=["wool"], image_file="simoneashley-devilwearsprada2-plaidtie.jpeg"),
    ]),
    ("The Hunger Games: Catching Fire", 2013, "Francis Lawrence", "action", "Effie Trinket", [
        dict(scene_label="Lavender ruffled reaping gown", designer="Alexander McQueen", era_decade="n/a",
             description="A voluminous lavender ruffled gown with an oversized collar, worn at the Quarter Quell reaping alongside Katniss and Peeta.",
             colors=["purple"], materials=["tulle"], image_file="effie-catchingfire-lavendermcqueen.jpg"),
        dict(scene_label="Lilac and gold satin peplum set", designer="", era_decade="n/a",
             description="A lilac satin peplum jacket with a gold silk lapel, part of Effie's color-blocked Capitol wardrobe.",
             colors=["purple", "gold"], materials=["satin", "brocade"], image_file="effie-catchingfire-lilacsatin.webp"),
        dict(scene_label="Magenta ruffled jacket", designer="", era_decade="n/a",
             description="A magenta ruffled jacket with an oversized rose corsage at the collar, worn with a pearl statement necklace.",
             colors=["pink"], materials=["silk"], image_file="effie-catchingfire-magentaruffle.jpg"),
        dict(scene_label="Pink layered ruffle gown", designer="", era_decade="n/a",
             description="A soft pink, heavily ruffled gown paired with an orange wig and an oversized floral fascinator.",
             colors=["pink"], materials=["organza"], image_file="effie-catchingfire-pinkruffles.jpg"),
        dict(scene_label="Monarch butterfly gown", designer="", era_decade="n/a",
             description="A gown entirely appliquéd in monarch butterflies, worn with a matching butterfly headpiece at a Capitol address.",
             colors=["gold"], materials=["lace"], image_file="effie-catchingfire-butterflygown.webp"),
    ]),
    ("The Hunger Games: Catching Fire", 2013, "Francis Lawrence", "action", "Katniss Everdeen", [
        dict(scene_label="Fire gown, twirl reveal", designer="Cinna", era_decade="n/a",
             description="A beaded ivory gown that catches fire mid-twirl to reveal a black Mockingjay-winged dress underneath.",
             colors=["ivory", "silver"], materials=["lace", "sequin"], image_file="katniss-catchingfire-firegown.jpg"),
        dict(scene_label="Red interview gown", designer="Cinna", era_decade="n/a",
             description="A one-shoulder red gown worn for the pre-Quarter-Quell television interview, the 'girl on fire' look.",
             colors=["red"], materials=["chiffon"], image_file="katniss-catchingfire-redinterviewgown.webp"),
    ]),
    ("The Hunger Games: Catching Fire", 2013, "Francis Lawrence", "action", "Johanna Mason", [
        dict(scene_label="Tattered gold gown, Capitol portrait", designer="", era_decade="n/a",
             description="A frayed, tattered gold gown for a stylized Capitol portrait, seated in a carved wooden chair.",
             colors=["gold"], materials=["chiffon"], image_file="johanna-catchingfire-goldtatteredgown.jpg"),
    ]),
    ("Kill Bill: Vol. 1", 2003, "Quentin Tarantino", "action", "O-Ren Ishii", [
        dict(scene_label="White kimono, snow garden duel", designer="", era_decade="n/a",
             description="A pure white kimono worn during the House of Blue Leaves snow garden sword duel.",
             colors=["white"], materials=["silk"], image_file="orenishii-killbill-whitekimono.webp"),
    ]),
    ("Kill Bill: Vol. 1", 2003, "Quentin Tarantino", "action", "Elle Driver", [
        dict(scene_label="Cream trench suit, hospital corridor", designer="", era_decade="n/a",
             description="A cream trench coat and matching pantsuit worn with an eyepatch, stalking a hospital corridor with a red umbrella.",
             colors=["ivory"], materials=["wool"], image_file="elledriver-killbill-creamtrench.webp"),
    ]),
    ("Alice in Wonderland", 2010, "Tim Burton", "fantasy", "Alice", [
        dict(scene_label="Blue tea party dress", designer="", era_decade="n/a",
             description="A periwinkle-blue pinafore dress worn at the Mad Hatter's sprawling, overgrown tea party.",
             colors=["blue"], materials=["cotton"], image_file="alice-aliceinwonderland-blueteapartydress.jpg"),
    ]),
    ("Beauty and the Beast", 2017, "Bill Condon", "fantasy", "Belle", [
        dict(scene_label="Gold floral celebration gown", designer="", era_decade="n/a",
             description="An ivory ballgown embroidered with gold and orange florals, worn dancing in the castle's final celebration.",
             colors=["gold", "ivory"], materials=["organza", "tulle"], image_file="belle-beautyandthebeast-goldfloralgown.webp"),
    ]),
    ("Breakfast at Tiffany's", 1961, "Blake Edwards", "romance", "Holly Golightly", [
        dict(scene_label="White embroidered gown, studio portrait", designer="", era_decade="1960s",
             description="A strapless white gown embroidered with gold floral vines, from a studio portrait session with a pair of poodles.",
             colors=["white", "gold"], materials=["satin"], image_file="holly-breakfastattiffanys-whiteembroideredgown.webp"),
    ]),
    ("The Haunting", 1999, "Jan de Bont", "horror", "Theo", [
        dict(scene_label="Red fur-trimmed coat", designer="", era_decade="n/a",
             description="A red satin coat with a voluminous fur collar, worn lounging in the mansion's gothic bedroom.",
             colors=["red"], materials=["fur"], image_file="theo-thehaunting-redfur.webp"),
        dict(scene_label="Taupe shaggy fur vest", designer="", era_decade="n/a",
             description="A shaggy taupe fur vest over black, worn wandering the mansion's shadowy halls.",
             colors=["khaki"], materials=["fur"], image_file="theo-thehaunting-taupefur.webp"),
    ]),
    ("The Mask of Zorro", 1998, "Martin Campbell", "action", "Elena Montero", [
        dict(scene_label="White lace riding dress", designer="", era_decade="1840s",
             description="A white lace-trimmed riding dress with puffed sleeves, worn on horseback outside the hacienda.",
             colors=["white"], materials=["lace", "cotton"], image_file="elena-maskofzorro-whitelace.jpg"),
    ]),
    ("Jerry Maguire", 1996, "Cameron Crowe", "drama", "Dorothy Boyd", [
        dict(scene_label="Black slip dress", designer="", era_decade="1990s",
             description="A simple black spaghetti-strap slip dress, worn in a quiet, warmly lit evening scene.",
             colors=["black"], materials=["satin"], image_file="dorothy-jerrymaguire-blackslipdress.jpg"),
    ]),
    ("Jupiter Ascending", 2015, "Lana Wachowski", "sci-fi", "Jupiter Jones", [
        dict(scene_label="Swarovski-crystal ballgown", designer="", era_decade="n/a",
             description="A white gown scattered with dark red crystal florals, worn descending toward a vast assembled crowd.",
             colors=["white", "red"], materials=["sequin", "tulle"], image_file="jupiter-jupiterascending-swarovskigown.jpg"),
    ]),
    ("10 Things I Hate About You", 1999, "Gil Junger", "coming-of-age", "Kat Stratford", [
        dict(scene_label="Slate-blue prom gown", designer="", era_decade="1990s",
             description="A slate-blue satin prom gown with a pearl necklace, worn descending a hotel staircase.",
             colors=["blue"], materials=["satin"], image_file="kat-10thingsihateaboutyou-blueprom.jpeg"),
    ]),
    ("Mirror Mirror", 2012, "Tarsem Singh", "fantasy", "Snow White", [
        dict(scene_label="Powder-blue bridal gown", designer="", era_decade="n/a",
             description="A powder-blue and navy wedding gown with an ornate tiara, from the film's closing celebration.",
             colors=["blue"], materials=["satin"], image_file="snowwhite-mirrormirror-bridalgown.jpeg"),
        dict(scene_label="Yellow floral ballgown", designer="", era_decade="n/a",
             description="A golden-yellow floral ballgown with mint puffed sleeves, an ornate storybook silhouette.",
             colors=["gold"], materials=["brocade"], image_file="snowwhite-mirrormirror-yellowfloralgown.jpeg"),
    ]),
    ("Mermaids", 1990, "Richard Benjamin", "drama", "Rachel Flax", [
        dict(scene_label="Silver sequined mermaid costume", designer="", era_decade="1960s",
             description="A silver sequined mermaid-inspired costume with a shell headpiece, worn for a dramatic entrance at a party.",
             colors=["silver"], materials=["sequin"], image_file="rachelflax-mermaids-silvermermaidgown.jpg"),
    ]),
    ("Shakespeare in Love", 1998, "John Madden", "romance", "Queen Elizabeth I", [
        dict(scene_label="Gold embroidered court gown", designer="", era_decade="1590s",
             description="A heavily gold-embroidered court gown with a wide ruff collar, worn presiding over the court in full regalia.",
             colors=["gold"], materials=["brocade"], image_file="queenelizabeth-shakespeareinlove-goldgown.jpeg"),
    ]),
    ("Shakespeare in Love", 1998, "John Madden", "romance", "Viola de Lesseps", [
        dict(scene_label="Gold embroidered ball gown", designer="", era_decade="1590s",
             description="A gold and cream embroidered gown with a jeweled headpiece, worn at a crowded Elizabethan court ball.",
             colors=["gold"], materials=["brocade"], image_file="viola-shakespeareinlove-goldembroideredgown.webp"),
        dict(scene_label="Turquoise beaded gown (costume display)", designer="", era_decade="1590s",
             description="A turquoise silk-velvet gown patterned in silver beadwork, photographed as a preserved costume piece on display.",
             colors=["turquoise"], materials=["velvet"], image_file="viola-shakespeareinlove-turquoisecostumedisplay.jpg"),
    ]),
    ("Marie Antoinette", 2006, "Sofia Coppola", "period-drama", "Marie Antoinette", [
        dict(scene_label="Powder-blue silk gown", designer="", era_decade="1770s",
             description="A powder-blue silk gown with a bow choker and matching gloves, worn inside the gilded halls of Versailles.",
             colors=["blue"], materials=["silk"], image_file="marieantoinette-marieantoinette-powderbluegown.webp"),
    ]),
    ("Moulin Rouge!", 2001, "Baz Luhrmann", "fashion-world", "Satine", [
        dict(scene_label="Red satin portrait", designer="", era_decade="n/a",
             description="A deep red satin gown in a glamour portrait against a tufted red banquette.",
             colors=["red"], materials=["satin"], image_file="satine-moulinrouge-redsatinportrait.jpg"),
        dict(scene_label="Black gown, diamond choker", designer="", era_decade="n/a",
             description="A black off-shoulder gown with a diamond choker, worn at a candlelit dinner scene.",
             colors=["black"], materials=["velvet"], image_file="satine-moulinrouge-blackdiamondgown.webp"),
    ]),
    ("Titanic", 1997, "James Cameron", "period-drama", "Rose DeWitt Bukater", [
        dict(scene_label="Pinstripe boarding suit", designer="", era_decade="1910s",
             description="A cream pinstripe suit with a black velvet collar and an oversized purple hat, worn boarding the ship.",
             colors=["white", "purple"], materials=["cotton"], image_file="rose-titanic-pinstripeboardingsuit.webp"),
    ]),
]


def run():
    db.init_db()

    conn = db.get_connection()
    cur = conn.cursor()
    cur.execute("TRUNCATE looks, characters, films RESTART IDENTITY CASCADE")
    conn.commit()

    for film_title, year, director, genre, char_name, looks in DATA:
        film_id = db.find_or_create_film(conn, film_title, year, director, genre)
        character_id = db.find_or_create_character(conn, char_name, film_id)
        for look in looks:
            # image_url is a full external link (verified before use, not downloaded);
            # image_file is a local file already copied into static/img/. image_url wins
            # if both happen to be set.
            if look.get("image_url"):
                image_url = look["image_url"]
            elif look.get("image_file"):
                image_url = f"/static/img/{look['image_file']}"
            else:
                image_url = ""
            db.insert_look(
                conn, character_id, look["scene_label"], look["designer"], look["era_decade"],
                look["description"], image_url, look["colors"], look["materials"],
                look.get("brand", ""), look.get("accessories", ""),
            )
    conn.commit()

    cur.execute("SELECT COUNT(*) AS c FROM films")
    film_count = cur.fetchone()["c"]
    cur.execute("SELECT COUNT(*) AS c FROM characters")
    char_count = cur.fetchone()["c"]
    cur.execute("SELECT COUNT(*) AS c FROM looks")
    look_count = cur.fetchone()["c"]
    conn.close()

    print(f"Seeded {film_count} films, {char_count} characters, {look_count} looks.")


if __name__ == "__main__":
    run()
